apiVersion: v1
kind: Service
metadata:
  name: facilitacaixa-api-service
  namespace: production
spec:
  type: LoadBalancer
  selector:
    app: facilitacaixa-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080